application: thecurrentsong
version: 6
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: assets/css

- url: /images
  static_dir: assets/images

- url: /js
  static_dir: assets/js

- url: .*
  script: urls.py




